### ISSUE TITLE
someone joins a scene after videos were added to it; they don't show. 

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/vdo.ninja#193]
scenes have no state.

**Comment by ersheff** [comment]
I assume this is related to the fact that I have to toggle Remove/Add per person in the director page to add them to a scene link that has just been opened. I have definitely run into situations where this caused a minor inconvenience (e.g. sent a scene link to a person that was only watching and not adding their own video, had to go through and toggle Remove/Add for all videos because the view-only person opened the link or had to refresh their browser after we'd all joined already).

**Comment by chrismarquardt** [comment]
+1, opening the scene=1 view won't show sources that have already been added to the scene by the director
