### ISSUE TITLE
iOS Cameras are lagging in OBS Browser window

### ISSUE THREAD

**Issue by jedeyenight5** [steveseguin/vdo.ninja#233]
Testing a browser source in Chrome works well. But when I insert a browser source into OBS, there is significant lag when the host is using an iOS device as a camera. This is a new issue that we have not seen while using weekly to host our live show. You can see an example of this in our most recent stream at the 11:15 mark here: https://www.twitch.tv/videos/685737110 

I got around this issue by opening the cameras in a browser and then inserting a screen capture around the camera but obviously that is a clunky fix.

Interestingly enough, the third person in our show was not using an iOS device as a camera and did not have this glitchy laggy issue so I can only assume that it is to do with iOS.

The browser sources misbehaving in OBS are 

https://obs.ninja/?view=S2Kxp43&codec=vp9&label=Charles&obsoff 
https://obs.ninja/?view=g5fK5WL&codec=vp9&label=Eric&obsoff

**Comment by chrismarquardt** [comment]
I've seen similar low-fps video when a guest was on wifi instead of a cabled connection and the requested video bitrate was too high. Almost always, hooking them up to an ethernet cable fixed the issue. As you're dealing with iOS devices that aren't easy to cable up, have you tried lowering video bitrate (&videobitrate=) and audio bitrate (&audiobitrate=) or downscale (&scale=50) to see if that helps? I find it amazing how small the bitrate can go while still looking good. And I'd personally prefer some minor compression artefacts to huge fps drops. I believe the default video bitrate is 2500kb/s, so there's big reduction potential. I'm running some guest connections on 250kbit/s because their upstream and wifi are too flaky. On the audio side, obsn's default is 256kb/s, but 64kb/s or even 32kb/s still sound amazingly good for voice. That's under 300kbit/s instead of almost 3Mbit/s and it's still usable for most

**Comment by jedeyenight5** [comment]
We actually use a power/Ethernet dongle on these iOS devices so they are
indeed plugged into routers directly. And again, this is the first time we
have ever had this issue in several months of use and it only occurred on
the 2 people who were using iPhones as cameras. The third person did not
have this issue.

What is the command to reduce video and audio bitrates?  I can try that but
I suspect this is a bug with iOS.

**Comment by steveseguin** [comment]
Please ensure that OBS has hardware acceleration turned on in the Advanced menu

Please note that iOS does not support VP9; just h264 and VP8.  Vp8 is software rendered and h264 is hardware rendered. This might change in the near future.

I sometimes find iOS is laggy initially, but it speeds up over time.  Ensuring that you are on good wifi, or better yet, using an ethenet adapter (as mentioned) will make a big difference.

**Comment by steveseguin** [comment]
Please also try using VP8 or lowering the resolution.

H264, the default video codec used by iOS, doesn't like to lower resolution if bitrates can't keep up,.  VP8 will use more battery on the iPhone, but it will scale the resolution more aggressive if the frame rates drop.

https://obs.ninja/?push=xxxx&quality=2

-- and to view -- 

https://obs.ninja/?view=xxxx&bitrate=6000 
or
https://obs.ninja/?view=xxxx&bitrate=6000&codec=vp8 
or
https://obs.ninja/?view=xxxx&bitrate=6000&codec=vp8&scale=50
