### ISSUE TITLE
Turn off video completely in group chat when not visible

### ISSUE THREAD

**Issue by b00rek** [steveseguin/vdo.ninja#68]
To preserve bandwidth and be able to have a larger number of people in group chat, turn off video completely when not visible.

Guests would communicate with audio only, director would have all video streams available in full quality.

**Comment by steveseguin** [comment]
I think this is a good approach for those looking to do more than 2 to 4 people in a group chat at a time. It's a bit complex for me to code, which implies prone to bugs, but this does seem like a direction worth going in.

**Comment by steveseguin** [comment]
Current status on this is that video quality for stream is set to "40kbps", for guests to view, which is pretty low.  They can "magnify" one stream at a time ,at a higher bitrate, so they can see details if needed.

I'm going to add the option to "stop" videos completely when not in view (ie: when selected their own video, for example).

This is almost done.

**Comment by steveseguin** [comment]
partially there.

Added a &novideo command (on alpha/beta) that makes it so only the audio is received;  This commmand can be used by the viewer, director, or whoever is in group chat.  ie: those viewing any video.

This completely prevents any video from being sent.  0 bps.  0 encoders used.

I will soon be able to add this to the group chat, so if not in the audio mixer, it will disable the video completely (not just go to 50kbps).

there are good reasons why at times you might want to go to 50kbps instead of disabling, but when switching speed is important, disabling may cause flicker/issues/low quality ramp up.
