### ISSUE TITLE
iOs 15.1.1 has major problems

### ISSUE THREAD

**Issue by DachsbauTV** [steveseguin/vdo.ninja#918]
Hi @steveseguin 

We ran into some issues today, when preparing for a show. The current iOs seems to not be able to connect to a room no matter what codec has been chosen.

Heard of that issue before?

We tried reopening several rooms with different codecs and with and without password plus compatibility mode

**Comment by steveseguin** [comment]
Hi @DachsbauTV ,

I can't say I've had that exact issue reported.  There have been some users mentioning iOS users appearing in the director's room, but not visible to other guests.  Maybe 3 reports of that since iOS 15 was released, but I can't easily reproduce it.  

I've also had 3 reports or so this month of users not able to access the service, which seems to be caused by a global routing issue.  I've created away around that issue on beta; **https://vdo.ninja/beta/?proxy** , which routes the connection via global edge nodes instead.

There's been a few mobile users this month having issues with UDP/Firewall issues on their mobile providers.  In one case, their mobile ISP reset their phone/network settings and it fixed the issue.

Some other users have had success using https://speedify.com to bypass UDP/Firewall issues.

I've made some changes to ALPHA at the moment with new media-track management.  https://vdo.ninja/alpha/  If there's an issue with that, it might work better.  

My iPhone is at 15.2 currently and I haven't had any issues with my testing this week.  I've created a room size of up to 9 last night on beta.

If you are still having issues, I'd be keen to debug the issue with you. I can provide you a debug link or have you join a room available here.

-steve

**Comment by DachsbauTV** [comment]
Hey Steve,

Thanks for the great support as usual  :)

We tried multiple iPhones 12(Pro) on 15.1.1 yesterday and they all had the same issue no matter what network they were on. The would connet to the room and then get dropped out of it in the very last step.

However, we've just tried the bete+proxy link and it is working!

Please tell me if I can provide more infos to help you find the issue, would be glad to help.

Thanks a lot again, you saved our show tonight :)

**Comment by steveseguin** [comment]
If &proxy is actually what fixed it for you, that's fantastic.  That would be a network ISP-level routing issue, if so.

However, if you join the room, and then suddenly get disconnected right before video appears, but the box appears, that might be a TCP or IPv6 issue instead. I added more TURN servers to beta that I have yet to push to production to address that issue, to try to improve coverage of those types of issues.

If this is the case, your iPhones might be going thru the TURN servers, rather than direct p2p. So another option in that case would be to use a different network or change privacy settings, or even use a service like speedify.com.  

If beta works though, that's great.  I really need to get it pushed into production soon.  Didn't expect there to be any TURN server issues on production.

Thank you for the issue report.

**Comment by DachsbauTV** [comment]
Oh sorry we were a little too enthusistic there, we still ran into the same problem, but I think I am little closer to the actual problem:
&codirector seems to be an issue.

As soon as we added the co-director and joined the room with director and co-director, the iPhone user couldn't connect anymore.
In a basic setup with &proxy it works fine.

**Comment by steveseguin** [comment]
I'm a tad perplexed as to what the issue could be currently. proxy has nothing to do with the codirector, so that's really strange.

One thing it might be is a hardware encoder issue.  iPhones have only 3 hardware encoders, and the director will use one, and each scene will use another.  If a co-director joins, they will also get a hardware encoder.

At some point the hardware encoders might run out and that may trigger an issue.  I thought I addressed this issue though, so it might not be the cause.

If you use &forceios or anything like that, it could use up the encoders even faster.

**Comment by DachsbauTV** [comment]
mh well yesterday both the director and the co-director had their cameras on in the room, but just now when I tested it, both cameras were off, so the iPhone wouldn't even have to encode?

**Comment by steveseguin** [comment]
I'm not quite sure at the moment what the cause is.

I have an iPhone 12 /w 15.2 here, so if you can create a set of links that cause the issue, I can duplicate the setup here and fix any issues.

**Comment by DachsbauTV** [comment]
Ok here I am again.
I've tried different scenarios now with this setup:
https://vdo.ninja/beta/?proxy&director=PrimeTime5&codirector=XXXX&codec=vp8
https://vdo.ninja/beta/?room=PrimeTime5

1. Android Phone: works fine
2. iPhone 11 15.1.1: works fine
3. iPhone 12 Pro 15.1.1.: can connect now (couldn't connect before) but doesn't receive audio or video from any of the directors.

feel free to join the room and test it. You should see two screens (me/codirector & Win10background/director) plus hear music playing on the director output

**Comment by steveseguin** [comment]
I joined the room as a co director and saw two screens, yes.

Looking at the code, the only thing that's specific to iOS 15 in the code is quality=0 (1080p).   With iOS 14 and under, the best quality you could get is &quality=1 (720p), but with iOS 15 i've allowed quality=0 to work. 

I don't have a problem with my iPhone 11 with iOS 15.2.

If you can't receive audio or video from any of the directors, it might be a networking issue.  Perhaps installing Speedify.com on the phone could help?  Using speedify at least as a test, to see if its a network issue, might be useful.

Are the two Iphones on the same network?  If on different networks, maybe that's related. Does changing networks help?

Sounds a bit like a network issue.  If the iPhone 12 has any sort of privacy mode enabled, it might be causing additional networking issues.  "IP Leaking" for example sometimes is blocked.  

I have a video link here if you want to test with; https://vdo.ninja/?view=FtwMqrp   I'll leave it up for the next 10 to 15 minutes or so I guess.

**Comment by DachsbauTV** [comment]
Hey @steveseguin 

Sorry for not replying anymore, it was generally getting to hectic before the show. We were lucky that the random call in guest didn't have an iPhone so we had no issues.

But back to your questions: we tried with the iPhone on the same network and on other networks and the issue was consistant. 
There was no privacy mode enabled whatsoever.

We will try with Speedify in the upcoming weeks.

Sorry for the unsatisfying bug report :/

**Comment by steveseguin** [comment]
I spent a couple nights hunting thru the code and doing a lot of tests, and I found a couple possible bugs.  Most of them were meshcast related, but there might be one race condition I found that could impact an iPhone.  Maybe the iPhone 12 is so far it triggers it -- unsure.

I did test on an iPhone 11 with 15.1 and didn't have any problems. =/

I pushed that code to beta, https://vdo.ninja/beta/  ; if you do a hard refresh and give it a shot, I'd be curious.

I'll probably be able to get ahold of an iPhone 12 Plus if the issues continue, but I'm not sure which version of iOS i'll have access to.

Thank you very much for the bug reports though --  I want things to be flawless and issue reports help me achieve that.

**Comment by DachsbauTV** [comment]
Hey @steveseguin 
Sorry it took a while especially with the holidays (and even more covid chaos) inbetween.

We did another test today with the current vdo.ninja version and the iPhone that had the problems and it seems like the issue is gone!

No matter which settings (especially codirector) it worked flawlessly even after a couple reconnects.

Thanks again fpr the help!
