### ISSUE TITLE
Feature Request: Autostart Default/saved Video and Audio (at least for directors)

### ISSUE THREAD

**Issue by freadZdead** [steveseguin/vdo.ninja#952]
Hi @steveseguin,

As per background: #947 

Basically, I'd be hoping for a URL switch that allows a director room view to autostart its own default or (even better) last used audio and video device to stream to the room participants.

Is this an easy thing to establish? I'd assume that Browser Security (in my case chromium-browser on raspbian) would take care of the User's control over camera and video (and would thus allow me to get a fully headless scenario if I always-enabled).

This would also be handy for normal room participants, but I would understand somebody claiming this to be a bit more murky in terms of consent/security?

Cheers,

Freddy

**Comment by steveseguin** [comment]
Hey freadZdead,

It's partly there.

For example, on beta, the follow will auto start the last used camera, assuming the camera permissions have already been granted.   (On beta, it will remember the last used device)

`https://vdo.ninja/beta/?autostart&webcam`

With the director, there is a bit more work needed, since the director doesn't have a main camera setup screen, and relies on the secondary settings menu instead.

You can however do:

 `https://vdo.ninja/beta/?director=XXXXXX&autostart&vd=1`

or 

 `https://vdo.ninja/beta/?director=XXXXXX&autostart&vd=obs`

to auto start a specified camera automatically as the default, but this won't use the last-used camera-- just whatever you specify manually.

vd=1 is the default system camera
vd=deviceName can be a partial string of a device name; you can get a list of those here: https://vdo.ninja/devices


To auto-start the last recalled device might just take me some more time;  I'm juggling quite a few requests currently, so let me know how urgent this is for you.

-steve

**Comment by freadZdead** [comment]
Hi @steveseguin,

Amazing - a) not super urgent, but also b) sounds already sufficient to me - will play with it over the next week and give you feedback, but for now - thank you very much, and good luck with the other issues!

Cheers,
Freddy

**Comment by freadZdead** [comment]
Hi @steveseguin ,

This is working really well for me - for my sake, no need to start the last device feature anymore, the fact that I can either go for default or for a specific device is all I need - thank you, please let me know when this feature leaves beta and goes into release :)!

Cheers,
Freddy
